version: "3"
services:
    analise-risco:
      build:
        context: analise-risco-api
        dockerfile: Dockerfile
      ports:
        - "8190:8080"
      environment:
        - LIST_PERM_URL=http://listas-perm-restricoes:8080
        - MOTOR_RISKSCORE_URL=http://motor-riskscore:8080
    listas-perm-restricoes:
      build:
        context: listas-perm-restr-api
        dockerfile: Dockerfile
      ports:
        - "8191:8080"
    motor-riskscore:
      build:
        context: motor-riskscore
        dockerfile: Dockerfile
      ports:
        - "8192:8080"