spring:
  application:
    name: analise-risco-api
motor-riskscore:
   url: ${MOTOR_RISKSCORE_URL:http://localhost:8192}
list-perm-restr:
  url: ${LIST_PERM_URL:http://localhost:8191}
score:
  ranges:
    - start: 300
      end: 10000
      status: APROVADO
    - start: 0
      end: 299
      status: NEGADO
